//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int idkhach { get; set; }
        public string tenkhach { get; set; }
        public string sodienthoai { get; set; }
        public string quoctich { get; set; }
        public string gioitinh { get; set; }
        public string ngaysinh { get; set; }
        public string cccd { get; set; }
        public string diachi { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string thanhtoan { get; set; }
        public int idphong { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
