//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int idnv { get; set; }
        public string tennv { get; set; }
        public string sodienthoainv { get; set; }
        public string gioitinhnv { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string loainguoidung { get; set; }
    }
}
